/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.vehiculos;

import controller.FuncionariosiudController;
import domain.Funcionariosiud;
import java.sql.SQLException;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Angel Puentes
 */
public class Main extends javax.swing.JFrame {
    
    private final FuncionariosiudController funcionariosiudController;
    private final static String[] COLUMNS = {"CEDULAF", "NOMBRES", "APELLIDOS", "ESTADOCIVIL",
            "SEXO", "DIRECCION", "TELEFONO", "FNACIMIENTO"};
    private final static String SELECCIONE = "--SELECCIONE--";
    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
        txtCedulafEdit.setEditable(false);
        funcionariosiudController = new FuncionariosiudController();
        listarFuncionariosiud();
        addListener();
    }

    private void listarFuncionariosiud() {
        
        cbxFuncionarios.removeAllItems();
        Funcionariosiud funcionariosiud1 = new Funcionariosiud();
        funcionariosiud1.setNombres(SELECCIONE);
        funcionariosiud1.setApellidos("");
        cbxFuncionarios.addItem(funcionariosiud1);
        DefaultTableModel defaultTableModel = new DefaultTableModel();
        for (String COLUMN : COLUMNS) {
            defaultTableModel.addColumn(COLUMN);
        }
        tblFuncionariosiud2.setModel(defaultTableModel);
        try {
            List<Funcionariosiud> funcionariosiud = funcionariosiudController.obtenerFuncionariosiud();
            if (funcionariosiud.isEmpty()){
                return;
            }
            defaultTableModel.setRowCount((funcionariosiud.size()));
            int row = 0;
            for (Funcionariosiud funcionarios : funcionariosiud){
                defaultTableModel.setValueAt(funcionarios.getCedulaf(), row, 0);
                defaultTableModel.setValueAt(funcionarios.getNombres(), row, 1);
                defaultTableModel.setValueAt(funcionarios.getApellidos(), row, 2);
                defaultTableModel.setValueAt(funcionarios.getEstadocivil(), row, 3);
                defaultTableModel.setValueAt(funcionarios.getSexo(), row, 4);
                defaultTableModel.setValueAt(funcionarios.getDireccion(), row, 5);
                defaultTableModel.setValueAt(funcionarios.getTelefono(), row, 6);
                defaultTableModel.setValueAt(funcionarios.getFnacimiento(), row, 7);
                row++;
                
                cbxFuncionarios.addItem(funcionarios);
            }
        } catch (SQLException ex) {
            ex.printStackTrace();
        }
    }
    private void addListener(){
        cbxFuncionarios.addItemListener(event -> {
             Funcionariosiud selectedFuncionarios = (Funcionariosiud) event.getItem();
             if (selectedFuncionarios.getNombres().equals(SELECCIONE)) {
                 txtCedulafEdit.setText("");
                 txtNombresEdit.setText("");
                 txtApellidosEdit.setText("");
                 txtEstadocivilEdit.setText("");
                 txtSexoEdit.setText("");
                 txtDireccionEdit.setText("");
                 txtTelefonoEdit.setText("");
                 txtFnacimientoEdit.setText("");
             }else {
                txtCedulafEdit.setText(selectedFuncionarios.getCedulaf());
                txtNombresEdit.setText(selectedFuncionarios.getNombres());
                txtApellidosEdit.setText(selectedFuncionarios.getApellidos());
                txtEstadocivilEdit.setText(selectedFuncionarios.getEstadocivil());
                txtSexoEdit.setText(selectedFuncionarios.getSexo());
                txtDireccionEdit.setText(selectedFuncionarios.getDireccion());
                txtTelefonoEdit.setText(selectedFuncionarios.getTelefono());
                txtFnacimientoEdit.setText(selectedFuncionarios.getFnacimiento());
                
             }
        });
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTPanes = new javax.swing.JTabbedPane();
        jPFuncionariosiud1 = new javax.swing.JPanel();
        jPFuncionariosiud = new javax.swing.JPanel();
        lblCedulaf = new javax.swing.JLabel();
        lblNombres = new javax.swing.JLabel();
        lblApellidos = new javax.swing.JLabel();
        lblEstadoCivil = new javax.swing.JLabel();
        lblSexo = new javax.swing.JLabel();
        lblDireccion = new javax.swing.JLabel();
        lblTelefono = new javax.swing.JLabel();
        lblFNacimiento = new javax.swing.JLabel();
        txtCedulaf = new javax.swing.JTextField();
        txtNombres = new javax.swing.JTextField();
        txtApellidos = new javax.swing.JTextField();
        txtEstadocivil = new javax.swing.JTextField();
        txtSexo = new javax.swing.JTextField();
        txtDireccion = new javax.swing.JTextField();
        txtTelefono = new javax.swing.JTextField();
        txtFnacimiento = new javax.swing.JTextField();
        btnGuardar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblFuncionariosiud2 = new javax.swing.JTable();
        jPFuncionariosiudEdit = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        cbxFuncionarios = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        txtCedulafEdit = new javax.swing.JTextField();
        lblBrandEdit = new javax.swing.JLabel();
        txtNombresEdit = new javax.swing.JTextField();
        txtApellidosEdit = new javax.swing.JTextField();
        lblModelEdit = new javax.swing.JLabel();
        lblAnhoEdit = new javax.swing.JLabel();
        lblColorEdit = new javax.swing.JLabel();
        txtSexoEdit = new javax.swing.JTextField();
        lblTransmisionEdit = new javax.swing.JLabel();
        txtDireccionEdit = new javax.swing.JTextField();
        btnActualizarEdit = new javax.swing.JButton();
        btnEliminarEdit = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtTelefonoEdit = new javax.swing.JTextField();
        txtFnacimientoEdit = new javax.swing.JTextField();
        txtEstadocivilEdit = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("APP FUNCIONARIOS");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 10, -1, 20));

        jPFuncionariosiud.setBorder(javax.swing.BorderFactory.createTitledBorder("Digite los siguientes campos"));

        lblCedulaf.setText("CÉDULA");

        lblNombres.setText("NOMBRES");

        lblApellidos.setText("APELLLIDOS");

        lblEstadoCivil.setText("ESTADO CIVIL");

        lblSexo.setText("SEXO");

        lblDireccion.setText("DIRECCION");

        lblTelefono.setText("TELEFONO");

        lblFNacimiento.setText("FECHA NACIMIENTO");

        txtCedulaf.setToolTipText("");

        txtTelefono.setToolTipText("");

        btnGuardar.setText("GUARDAR");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPFuncionariosiudLayout = new javax.swing.GroupLayout(jPFuncionariosiud);
        jPFuncionariosiud.setLayout(jPFuncionariosiudLayout);
        jPFuncionariosiudLayout.setHorizontalGroup(
            jPFuncionariosiudLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPFuncionariosiudLayout.createSequentialGroup()
                .addGroup(jPFuncionariosiudLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPFuncionariosiudLayout.createSequentialGroup()
                        .addGap(196, 196, 196)
                        .addComponent(btnGuardar))
                    .addGroup(jPFuncionariosiudLayout.createSequentialGroup()
                        .addGroup(jPFuncionariosiudLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPFuncionariosiudLayout.createSequentialGroup()
                                .addComponent(txtCedulaf, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtNombres, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPFuncionariosiudLayout.createSequentialGroup()
                                .addComponent(lblCedulaf)
                                .addGap(79, 79, 79)
                                .addComponent(lblNombres, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(jPFuncionariosiudLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblApellidos)
                            .addComponent(txtApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)
                        .addGroup(jPFuncionariosiudLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtEstadocivil, javax.swing.GroupLayout.DEFAULT_SIZE, 81, Short.MAX_VALUE)
                            .addComponent(lblEstadoCivil, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(27, 27, 27)
                        .addGroup(jPFuncionariosiudLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblSexo)
                            .addComponent(txtSexo, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPFuncionariosiudLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPFuncionariosiudLayout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addComponent(lblDireccion))
                            .addGroup(jPFuncionariosiudLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(txtDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPFuncionariosiudLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblTelefono)
                            .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPFuncionariosiudLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblFNacimiento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtFnacimiento))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPFuncionariosiudLayout.setVerticalGroup(
            jPFuncionariosiudLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPFuncionariosiudLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPFuncionariosiudLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCedulaf)
                    .addComponent(lblNombres)
                    .addComponent(lblApellidos)
                    .addComponent(lblEstadoCivil)
                    .addComponent(lblSexo)
                    .addComponent(lblDireccion)
                    .addComponent(lblTelefono)
                    .addComponent(lblFNacimiento))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPFuncionariosiudLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCedulaf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNombres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtEstadocivil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtFnacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addComponent(btnGuardar)
                .addContainerGap())
        );

        lblCedulaf.getAccessibleContext().setAccessibleDescription("");

        tblFuncionariosiud2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tblFuncionariosiud2);

        javax.swing.GroupLayout jPFuncionariosiud1Layout = new javax.swing.GroupLayout(jPFuncionariosiud1);
        jPFuncionariosiud1.setLayout(jPFuncionariosiud1Layout);
        jPFuncionariosiud1Layout.setHorizontalGroup(
            jPFuncionariosiud1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPFuncionariosiud1Layout.createSequentialGroup()
                .addGroup(jPFuncionariosiud1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPFuncionariosiud, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1095, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPFuncionariosiud1Layout.setVerticalGroup(
            jPFuncionariosiud1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPFuncionariosiud1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPFuncionariosiud, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 327, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTPanes.addTab("Crear funcionario", jPFuncionariosiud1);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Modifique los siguientes campos"));

        jLabel2.setText("FUNCIONARIOS");

        jLabel3.setText("CEDULA");

        lblBrandEdit.setText("NOMBRES");

        lblModelEdit.setText("APELLIDOS");

        lblAnhoEdit.setText("ESTADO CIVIL");

        lblColorEdit.setText("SEXO");

        lblTransmisionEdit.setText("DIRECCION");

        btnActualizarEdit.setText("ACTUALIZAR");
        btnActualizarEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarEditActionPerformed(evt);
            }
        });

        btnEliminarEdit.setText("ELIMINAR");
        btnEliminarEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarEditActionPerformed(evt);
            }
        });

        jLabel4.setText("TELEFONO");

        jLabel5.setText("FECHA NACIMIENTO");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnActualizarEdit, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtCedulafEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtNombresEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblBrandEdit))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(lblModelEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(96, 96, 96))
                                    .addComponent(txtApellidosEdit))))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(77, 77, 77)
                                .addComponent(btnEliminarEdit))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(9, 9, 9)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(lblAnhoEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(55, 55, 55))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(txtEstadocivilEdit)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblColorEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtSexoEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtDireccionEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblTransmisionEdit))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtTelefonoEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addComponent(txtFnacimientoEdit)))))
                    .addComponent(cbxFuncionarios, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cbxFuncionarios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(lblBrandEdit)
                    .addComponent(lblModelEdit)
                    .addComponent(lblAnhoEdit)
                    .addComponent(lblColorEdit)
                    .addComponent(lblTransmisionEdit)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCedulafEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNombresEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtApellidosEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSexoEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDireccionEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTelefonoEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtFnacimientoEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtEstadocivilEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 315, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnActualizarEdit)
                    .addComponent(btnEliminarEdit))
                .addContainerGap())
        );

        txtTelefonoEdit.getAccessibleContext().setAccessibleName("");

        javax.swing.GroupLayout jPFuncionariosiudEditLayout = new javax.swing.GroupLayout(jPFuncionariosiudEdit);
        jPFuncionariosiudEdit.setLayout(jPFuncionariosiudEditLayout);
        jPFuncionariosiudEditLayout.setHorizontalGroup(
            jPFuncionariosiudEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPFuncionariosiudEditLayout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPFuncionariosiudEditLayout.setVerticalGroup(
            jPFuncionariosiudEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPFuncionariosiudEditLayout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTPanes.addTab("Editar Funcionario", jPFuncionariosiudEdit);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1105, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 502, Short.MAX_VALUE)
        );

        jTPanes.addTab("tab3", jPanel2);

        getContentPane().add(jTPanes, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 1110, 530));
        jTPanes.getAccessibleContext().setAccessibleName("Editar Funcionario");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnActualizarEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarEditActionPerformed
       
//        if (txtCedulaf.getText().trim().length() == 0) {
//            JOptionPane.showMessageDialog(null, "Digite el npumero de documento ");
//            txtCedulaf.requestFocus();
//            return;
//        }
        
        if (txtCedulaf.getText().trim().length() == 0) {
            JOptionPane.showMessageDialog(null, "Digite el núumero de documento ");
            txtCedulaf.requestFocus();
            return;
        }

        if (txtNombresEdit.getText().trim().length() == 0) {
            JOptionPane.showMessageDialog(null, "Digite los nombres ");
            txtNombresEdit.requestFocus();
            return;
        }

        if (txtApellidosEdit.getText().trim().length() == 0) {
            JOptionPane.showMessageDialog(null, "Digite los apellidos ");
            txtApellidosEdit.requestFocus();
            return;
        }

        if (txtEstadocivilEdit.getText().trim().length() == 0) {
            JOptionPane.showMessageDialog(null, "Digite el estdo civil ");
            txtEstadocivilEdit.requestFocus();
            return;
        }

        if (txtSexoEdit.getText().trim().length() == 0) {
            JOptionPane.showMessageDialog(null, "Digite el sexo ");
            txtSexoEdit.requestFocus();
            return;
        }

        if (txtDireccionEdit.getText().trim().length() == 0) {
            JOptionPane.showMessageDialog(null, "Digite la direccion ");
            txtDireccionEdit.requestFocus();
            return;
        }

        if (txtTelefonoEdit.getText().trim().length() == 0) {
            JOptionPane.showMessageDialog(null, "Digite el telefono ");
            txtTelefonoEdit.requestFocus();
            return;
        }

        if (txtFnacimientoEdit.getText().trim().length() == 0) {
            JOptionPane.showMessageDialog(null, "Digite la fecha de nacimiento ");
            txtFnacimientoEdit.requestFocus();
            return;
        }

            Funcionariosiud funcionariosiud = new Funcionariosiud();
            funcionariosiud.setCedulaf(txtCedulafEdit.getText().trim());
            funcionariosiud.setNombres(txtNombresEdit.getText().trim());
            funcionariosiud.setApellidos(txtApellidosEdit.getText().trim());
            funcionariosiud.setEstadocivil(txtEstadocivilEdit.getText().trim());
            funcionariosiud.setSexo(txtSexoEdit.getText().trim());
            funcionariosiud.setDireccion(txtDireccionEdit.getText().trim());
            funcionariosiud.setTelefono(txtTelefonoEdit.getText().trim());
            funcionariosiud.setFnacimiento(txtFnacimientoEdit.getText().trim());
            
            int opt = JOptionPane.showConfirmDialog(null, "¿Desea actualizar los datos?",
                        "Confirmar salida", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        try {
            funcionariosiudController.actualizarFuncionariosiud(txtCedulaf.getText(),funcionariosiud);
            txtCedulaf.setText("");
            txtNombres.setText("");
            txtApellidos.setText("");
            txtEstadocivil.setText("");
            txtSexo.setText("");
            txtDireccion.setText("");
            txtTelefono.setText("");
            txtFnacimiento.setText("");
            listarFuncionariosiud();
            JOptionPane.showMessageDialog(null,"Funcionario actualizado con éxito");
            
            
        } catch (SQLException ex) {
            ex.printStackTrace();
        }
        
    }//GEN-LAST:event_btnActualizarEditActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed

        if (txtCedulaf.getText().trim().length() == 0) {
            JOptionPane.showMessageDialog(null, "Digite el npumero de documento ");
            txtCedulaf.requestFocus();
            return;
        }

        if (txtNombres.getText().trim().length() == 0) {
            JOptionPane.showMessageDialog(null, "Digite los nombres ");
            txtNombres.requestFocus();
            return;
        }

        if (txtApellidos.getText().trim().length() == 0) {
            JOptionPane.showMessageDialog(null, "Digite los apellidos ");
            txtApellidos.requestFocus();
            return;
        }

        if (txtEstadocivil.getText().trim().length() == 0) {
            JOptionPane.showMessageDialog(null, "Digite el estdo civil ");
            txtEstadocivil.requestFocus();
            return;
        }

        if (txtSexo.getText().trim().length() == 0) {
            JOptionPane.showMessageDialog(null, "Digite el sexo ");
            txtSexo.requestFocus();
            return;
        }

        if (txtDireccion.getText().trim().length() == 0) {
            JOptionPane.showMessageDialog(null, "Digite la direccion ");
            txtDireccion.requestFocus();
            return;
        }

        if (txtTelefono.getText().trim().length() == 0) {
            JOptionPane.showMessageDialog(null, "Digite el telefono ");
            txtTelefono.requestFocus();
            return;
        }

        if (txtFnacimiento.getText().trim().length() == 0) {
            JOptionPane.showMessageDialog(null, "Digite la fecha de nacimiento ");
            txtFnacimiento.requestFocus();
            return;
        }

        try {

            Funcionariosiud funcionariosiud = new Funcionariosiud();
            funcionariosiud.setCedulaf(txtCedulaf.getText().trim());
            funcionariosiud.setNombres(txtNombres.getText().trim());
            funcionariosiud.setApellidos(txtApellidos.getText().trim());
            funcionariosiud.setEstadocivil(txtEstadocivil.getText().trim());
            funcionariosiud.setSexo(txtSexo.getText().trim());
            funcionariosiud.setDireccion(txtDireccion.getText().trim());
            funcionariosiud.setTelefono(txtTelefono.getText().trim());
            funcionariosiud.setFnacimiento(txtFnacimiento.getText().trim());

            funcionariosiudController.crear(funcionariosiud);
            txtCedulafEdit.setText("");
            txtNombresEdit.setText("");
            txtApellidosEdit.setText("");
            txtEstadocivilEdit.setText("");
            txtSexoEdit.setText("");
            txtDireccionEdit.setText("");
            txtTelefonoEdit.setText("");
            txtFnacimientoEdit.setText("");
            listarFuncionariosiud();
            JOptionPane.showMessageDialog(null,"Funcionario creado con éxito");
            
            
        } catch (SQLException ex) {
            ex.printStackTrace();
        }

    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnEliminarEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarEditActionPerformed

        if (txtCedulaf.getText().trim().length() == 0) {
            JOptionPane.showMessageDialog(null, "Seleccione un funcionario de la lista ");
            txtCedulaf.requestFocus();
            return;
        }

        int opt = JOptionPane.showConfirmDialog(null, "¿Está seguro de eliminar el funcionario?",
                "Confirmar salida", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        if (opt == 0) {

            try {
                funcionariosiudController.eliminarFuncionariosiud(txtCedulaf.getText());
                txtCedulafEdit.setText("");
                txtNombresEdit.setText("");
                txtApellidosEdit.setText("");
                txtEstadocivilEdit.setText("");
                txtSexoEdit.setText("");
                txtDireccionEdit.setText("");
                txtTelefonoEdit.setText("");
                txtFnacimientoEdit.setText("");
                listarFuncionariosiud();
                JOptionPane.showMessageDialog(null, "Funcionario eliminado con éxito");
            } catch (SQLException ex) {
                ex.printStackTrace();
            }
        }
    }//GEN-LAST:event_btnEliminarEditActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizarEdit;
    private javax.swing.JButton btnEliminarEdit;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JComboBox<Funcionariosiud> cbxFuncionarios;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPFuncionariosiud;
    private javax.swing.JPanel jPFuncionariosiud1;
    private javax.swing.JPanel jPFuncionariosiudEdit;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTPanes;
    private javax.swing.JLabel lblAnhoEdit;
    private javax.swing.JLabel lblApellidos;
    private javax.swing.JLabel lblBrandEdit;
    private javax.swing.JLabel lblCedulaf;
    private javax.swing.JLabel lblColorEdit;
    private javax.swing.JLabel lblDireccion;
    private javax.swing.JLabel lblEstadoCivil;
    private javax.swing.JLabel lblFNacimiento;
    private javax.swing.JLabel lblModelEdit;
    private javax.swing.JLabel lblNombres;
    private javax.swing.JLabel lblSexo;
    private javax.swing.JLabel lblTelefono;
    private javax.swing.JLabel lblTransmisionEdit;
    private javax.swing.JTable tblFuncionariosiud2;
    private javax.swing.JTextField txtApellidos;
    private javax.swing.JTextField txtApellidosEdit;
    private javax.swing.JTextField txtCedulaf;
    private javax.swing.JTextField txtCedulafEdit;
    private javax.swing.JTextField txtDireccion;
    private javax.swing.JTextField txtDireccionEdit;
    private javax.swing.JTextField txtEstadocivil;
    private javax.swing.JTextField txtEstadocivilEdit;
    private javax.swing.JTextField txtFnacimiento;
    private javax.swing.JTextField txtFnacimientoEdit;
    private javax.swing.JTextField txtNombres;
    private javax.swing.JTextField txtNombresEdit;
    private javax.swing.JTextField txtSexo;
    private javax.swing.JTextField txtSexoEdit;
    private javax.swing.JTextField txtTelefono;
    private javax.swing.JTextField txtTelefonoEdit;
    // End of variables declaration//GEN-END:variables
}
